  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Header from "./myReusableComponents/Header";
  import { Toaster } from "@/components/ui/sonner";
  import StoreEmail from "@/components/ui/StoreEmail";
  import { client } from '@/lib/appwriteConfig';
  import { Analytics } from "@vercel/analytics/next"
import Footer from "@/components/Footer";

  if (typeof window !== 'undefined') {
    const sessionCookie = document.cookie;
    client.setSession(sessionCookie);
  }

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
      <body className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}>
  <Header />
  <StoreEmail /> {/* ✅ Add this to store email on every load */}
          <main className="flex-grow">
  {children}
  </main>
  <Footer /> {/* ✅ This is what was missing */}
  <Toaster visibleToasts={3} /> {/* 👈 limit stacking to 3 */}
  <Analytics /> {/* 👈 Mount it here so it loads globally */}
</body>
      </html>
    );
  }

